data:
  dataset: BRCA
  k_cutoff: 8
  top_genes: 3000
mode: imputation
model:
  clus_num_iters: 20
  dic_hidden: 64
  feat_hidden1: 64
  feat_hidden2: 32
  gcn_hidden: 64
  latent_dim: 16
  mask_rate: 0.5
  momentum_rate: 0.998
  num_kmeans: 5
  p_drop: 0.2
  project_dim: 32
  replace_rate: 0.1
  t: 2
  topk: 50
seed: 3407
train:
  decay: 0.001
  epochs: 1000
  gradient_clipping: 5.0
  lr: 0.001
  t_step: 50
  w_mean: 0.1
  w_recon: 1
  w_tri: 1
