data:
  dataset: HM
  k_cutoff: 6
  top_genes: 3000
mode: imputation
model:
  clus_num_iters: 20
  dic_hidden: 64
  feat_hidden1: 64
  feat_hidden2: 32
  gcn_hidden: 64
  latent_dim: 16
  mask_rate: 0.2
  momentum_rate: 0.98
  num_kmeans: 3
  p_drop: 0.2
  project_dim: 32
  replace_rate: 0.1
  t: 2
  topk: 50
seed: 3407
train:
  decay: 0.001
  epochs: 500
  gradient_clipping: 5.0
  lr: 0.001
  t_step: 50
  w_mean: 0.07999999999999999
  w_recon: 0.6
  w_tri: 0.32000000000000006
